spring:
  datasource:
    url: jdbc:h2:file:${project.dir.data}/database/comicbook
    driverClassName: org.h2.Driver
    name: comicbook
    password: comicbook
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
server:
  port: 2608
  servlet:
    context-path: /comicbook
project:
  dir:
    root: ${user.home}/comicbook
    data: ${project.dir.root}/data